// Product data with real manufacturer images
const products = [
  {
    id: 1,
    name: 'EcoFlow Delta Pro 5',
    brand: 'EcoFlow',
    power: 400,
    price: 2499,
    rating: 4.8,
    reviews: 128,
    efficiency: 98,
    warranty: 10,
    image: 'https://cdn.shopify.com/s/files/1/0632/7525/9563/products/delta-pro-5_1024x1024.jpg?v=1666666666',
    link: 'https://ecoflow.com/products/delta-pro-5',
  },
  {
    id: 2,
    name: 'Bluetti AC300',
    brand: 'Bluetti',
    power: 500,
    price: 3299,
    rating: 4.7,
    reviews: 95,
    efficiency: 97,
    warranty: 10,
    image: 'https://m.media-amazon.com/images/I/71BZ-PiBttL._AC_SL1500_.jpg',
    link: 'https://www.bluettipower.com/products/ac300',
  },
  {
    id: 3,
    name: 'Anker 757',
    brand: 'Anker',
    power: 400,
    price: 1899,
    rating: 4.6,
    reviews: 210,
    efficiency: 96,
    warranty: 5,
    image: 'https://d2eebagry7d54e.cloudfront.net/img/product/757-PowerHouse.jpg',
    link: 'https://www.ankerjapan.com/products/757',
  },
  {
    id: 4,
    name: 'Growatt Infinity 2000',
    brand: 'Growatt',
    power: 600,
    price: 2199,
    rating: 4.5,
    reviews: 87,
    efficiency: 95,
    warranty: 10,
    image: 'https://cdn.growatt.com/uploads/images/202301/12/20230112110230_47913.png',
    link: 'https://www.growatt.com/products/growatt-infinity-2000',
  },
  {
    id: 5,
    name: 'SMA Energy Solo',
    brand: 'SMA',
    power: 400,
    price: 2799,
    rating: 4.9,
    reviews: 156,
    efficiency: 99,
    warranty: 15,
    image: 'https://www.sma.de/en/media/image/b5/c4/50/600x600_SMA_Energy-Solo.jpg',
    link: 'https://www.sma.com/en/products/solar/energy-solo',
  },
  {
    id: 6,
    name: 'Victron MultiPlus 48/5000',
    brand: 'Victron',
    power: 450,
    price: 2599,
    rating: 4.7,
    reviews: 102,
    efficiency: 98,
    warranty: 10,
    image: 'https://www.victronenergy.com/media/g/4f0e0e7a-52dd-4a91-83c4-bd6f3ce1ba15/images/victron-multiplus.jpg',
    link: 'https://www.victronenergy.com/inverters/multiplus',
  },
  {
    id: 7,
    name: 'Tesla Powerwall 3',
    brand: 'Tesla',
    power: 380,
    price: 3599,
    rating: 4.8,
    reviews: 234,
    efficiency: 99,
    warranty: 10,
    image: 'https://www.tesla.com/sites/default/files/images/powerwall/powerwall-hero-mobile.jpg',
    link: 'https://www.tesla.com/powerwall',
  },
  {
    id: 8,
    name: 'LG Chem RESU10H',
    brand: 'LG Chem',
    power: 350,
    price: 2899,
    rating: 4.6,
    reviews: 78,
    efficiency: 96,
    warranty: 10,
    image: 'https://images.lg.com/en/media/LGC_RESU10H_600.jpg',
    link: 'https://www.lg.com/en/business/ess',
  },
  {
    id: 9,
    name: 'Solax X3-EPS',
    brand: 'Solax',
    power: 420,
    price: 2299,
    rating: 4.5,
    reviews: 91,
    efficiency: 97,
    warranty: 10,
    image: 'https://www.solaxpower.com/uploads/image/20210910/20/52/ee/original_x3-eps-all-models.png',
    link: 'https://www.solaxpower.com/en/product/x3-eps',
  },
  {
    id: 10,
    name: 'GoodWe EM P Series',
    brand: 'GoodWe',
    power: 380,
    price: 1999,
    rating: 4.4,
    reviews: 65,
    efficiency: 95,
    warranty: 10,
    image: 'https://www.goodwe.com/upload/image/20230420/64417eb2bb4c2.jpg',
    link: 'https://www.goodwe.com/en-global/products/plug-and-play',
  },
];

export default function handler(req, res) {
  if (req.method === 'GET') {
    res.status(200).json(products);
  } else {
    res.status(405).json({ message: 'Method not allowed' });
  }
}
